/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: points.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "points.pb-c.h"
void   player__init
                     (Player         *message)
{
  static const Player init_value = PLAYER__INIT;
  *message = init_value;
}
size_t player__get_packed_size
                     (const Player *message)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t player__pack
                     (const Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t player__pack_to_buffer
                     (const Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Player *
       player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Player *)
     protobuf_c_message_unpack (&player__descriptor,
                                allocator, len, data);
}
void   player__free_unpacked
                     (Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   simple_message__init
                     (SimpleMessage         *message)
{
  static const SimpleMessage init_value = SIMPLE_MESSAGE__INIT;
  *message = init_value;
}
size_t simple_message__get_packed_size
                     (const SimpleMessage *message)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t simple_message__pack
                     (const SimpleMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t simple_message__pack_to_buffer
                     (const SimpleMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &simple_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SimpleMessage *
       simple_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SimpleMessage *)
     protobuf_c_message_unpack (&simple_message__descriptor,
                                allocator, len, data);
}
void   simple_message__free_unpacked
                     (SimpleMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &simple_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor player__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Player, id),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Player, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned player__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = score */
};
static const ProtobufCIntRange player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Player",
  "Player",
  "Player",
  "",
  sizeof(Player),
  2,
  player__field_descriptors,
  player__field_indices_by_name,
  1,  player__number_ranges,
  (ProtobufCMessageInit) player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor simple_message__field_descriptors[1] =
{
  {
    "players",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SimpleMessage, n_players),
    offsetof(SimpleMessage, players),
    &player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned simple_message__field_indices_by_name[] = {
  0,   /* field[0] = players */
};
static const ProtobufCIntRange simple_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor simple_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Simple_message",
  "SimpleMessage",
  "SimpleMessage",
  "",
  sizeof(SimpleMessage),
  1,
  simple_message__field_descriptors,
  simple_message__field_indices_by_name,
  1,  simple_message__number_ranges,
  (ProtobufCMessageInit) simple_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
